apiVersion: v1
kind: Service
metadata:
  name: 2-node-demo-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: 2-node-demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2-node-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 2-node-demo-app
  template:
    metadata:
      labels:
        app: 2-node-demo-app
    spec:
      containers:
      - name: 2-node-demo-app
        image: nnamuhcs/2-node-demo-app01:latest
        ports:
        - containerPort: 8080
